-- MySQL Script generated by MySQL Workbench
-- Wed Mar 29 11:15:43 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`users` ;

CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `idusers` INT NOT NULL AUTO_INCREMENT,
  `user` VARCHAR(45) NOT NULL,
  `pasword` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `plan_details` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idusers`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`movies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`movies` ;

CREATE TABLE IF NOT EXISTS `mydb`.`movies` (
  `idmovies` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `genre` VARCHAR(45) NULL,
  `image` LONGTEXT NOT NULL,
  `category` VARCHAR(45) NOT NULL,
  `year` INT NULL,
  PRIMARY KEY (`idmovies`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`actors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`actors` ;

CREATE TABLE IF NOT EXISTS `mydb`.`actors` (
  `idactors` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  `birthday` DATE NOT NULL,
  PRIMARY KEY (`idactors`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`rel_movies_users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`rel_movies_users` ;

CREATE TABLE IF NOT EXISTS `mydb`.`rel_movies_users` (
  `users_idusers` INT NOT NULL,
  `movies_idmovies` INT NOT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`, `users_idusers`),
  INDEX `fk_users_has_movies_movies1_idx` (`movies_idmovies` ASC) VISIBLE,
  INDEX `fk_users_has_movies_users_idx` (`users_idusers` ASC) VISIBLE,
  CONSTRAINT `fk_users_has_movies_users`
    FOREIGN KEY (`users_idusers`)
    REFERENCES `mydb`.`users` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_movies_movies1`
    FOREIGN KEY (`movies_idmovies`)
    REFERENCES `mydb`.`movies` (`idmovies`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.` rel_movies_actors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.` rel_movies_actors` ;

CREATE TABLE IF NOT EXISTS `mydb`.` rel_movies_actors` (
  `movies_idmovies` INT NOT NULL,
  `actors_idactors` INT NOT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  INDEX `fk_movies_has_actors_actors1_idx` (`actors_idactors` ASC) VISIBLE,
  INDEX `fk_movies_has_actors_movies1_idx` (`movies_idmovies` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_movies_has_actors_movies1`
    FOREIGN KEY (`movies_idmovies`)
    REFERENCES `mydb`.`movies` (`idmovies`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_movies_has_actors_actors1`
    FOREIGN KEY (`actors_idactors`)
    REFERENCES `mydb`.`actors` (`idactors`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
